version: "3.9"

services:
  db:
    build: ./Backend/database
    ports:
      - "27017:27017"

  backend:
    build: ./Backend
    ports:
      - "80:80"
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  test:
    build: ./Testing
    depends_on:
      - frontend
      - backend
